"""Render the Health Monitor app icon as PNG (192 and 512) from the same geometry as the SVG favicon.
Deterministic, no model calls. Writes src/icons.js with base64 data."""
import base64, io, math
from PIL import Image, ImageDraw

TILE = (0x55, 0x48, 0x8d)
def heart_points(cx, cy, s, n=240):
    pts = []
    for i in range(n):
        t = 2 * math.pi * i / n
        x = 16 * math.sin(t) ** 3
        y = 13 * math.cos(t) - 5 * math.cos(2 * t) - 2 * math.cos(3 * t) - math.cos(4 * t)
        pts.append((cx + x * s, cy - y * s))
    return pts

def render(size, maskable=False):
    k = 4  # supersample
    S = size * k
    img = Image.new("RGB", (S, S), TILE) if maskable else Image.new("RGBA", (S, S), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    if not maskable:
        d.rounded_rectangle([0, 0, S - 1, S - 1], radius=int(S * 7 / 32), fill=TILE)
    scale = 0.62 if maskable else 0.78        # maskable icons keep content inside the safe zone
    unit = S * scale / 32
    off = (S - 32 * unit) / 2
    P = lambda x, y: (off + x * unit, off + y * unit)
    d.polygon(heart_points(*P(16, 14.2), unit * 0.8), fill="white")
    line = [P(2.5, 16.0), P(10.8, 16.0), P(13.0, 11.2), P(16.2, 21.0), P(18.8, 13.8), P(20.3, 16.0), P(29.5, 16.0)]
    d.line(line, fill=TILE, width=int(unit * 2.1), joint="curve")
    return img.resize((size, size), Image.LANCZOS)

def b64(img):
    buf = io.BytesIO(); img.save(buf, "PNG", optimize=True); return base64.b64encode(buf.getvalue()).decode()

icons = {"ICON_192": b64(render(192)), "ICON_512": b64(render(512)), "ICON_MASKABLE_512": b64(render(512, maskable=True))}
render(512).save("icon-preview.png")
with open("src/icons.js", "w", encoding="utf-8") as f:
    f.write("// Generated by tools/make_icon.py. White heart with a heartbeat line on the Deep-sleep violet tile.\n")
    for k, v in icons.items():
        f.write(f'export const {k} = "{v}";\n')
print({k: len(v) for k, v in icons.items()})
